### ISSUE TITLE
Support ES6

### ISSUE THREAD

**Issue by stereoplegic** [meetalva/alva#640] opened 2018-10-25 18:05 UTC
**Is your feature request related to a problem? Please describe.**
Typescript pattern/library support is limiting for devs

**Describe the solution you'd like**
ES6 support would accommodate a much wider range of devs (e.g. React w/ ES6/Flow)

**Comment by marionebl** [comment] 2018-12-19 07:59
Thanks for your suggestion! 

This is a duplicate of #284. I'll close this to keep the discussion centered.

**Closed by marionebl** 2018-12-19 07:59 UTC
Labels: type: feature
