### ISSUE TITLE
JS Error: Cannot create BrowserWindow before app is ready

### ISSUE THREAD

**Issue by tobiastornros** [meetalva/alva#137] opened 2017-12-22 07:08 UTC
Cannot create BrowserWindow before app is ready error. Bug related to Electron.js

## Bug description
A JavaScript error occurred in the main thread on startup in electon.js. See screenshot for more details.

## How to reproduce

- Happens during startup, so try to start the app.

## Screenshots

<img width="462" alt="screen shot 2017-12-22 at 07 50 49" src="https://user-images.githubusercontent.com/17402497/34288586-5ff952ea-e6ee-11e7-9744-24d7cd2b6bfa.png">

## Info

App version: 0.6.0
OS X version: 10.12.6 (16G1036)

**Comment by LKuechler** [comment] 2017-12-22 08:15
This is a strange bug. The creation of the BrowserWindow is called in a callback from Electron that says that it is ready.
I can currently not reproduce it on my machine but it could be because i have a newer OSX version.

**Comment by Jumace** [comment] 2017-12-22 09:16
I've tried to reproduce the bug on my machine.

OS X 10.12.6
Alva 0.6.0

But I can't reproduce it. Everything works fine.
@tobiastornros: Do you have may more information on how to reproduce it?

I have an idea about the source of the issue but would be nice to be able to reproduce it ;)

**Comment by tobiastornros** [comment] 2017-12-22 10:28
@Jumace I can´t reproduce it now. Maybe it only occurs on the first startup after installation. I can try later today.

**Comment by Jumace** [comment] 2017-12-22 10:35
@tobiastornros thanks for the feedback. I've read in the issues of another electron application that the same error occurred after every restart of the operating system.

Maybe that is worth a try.

**Comment by TheReincarnator** [comment] 2018-03-29 09:59
I cannot reproduce this as well, neither with existing, nor with invalid, nor with missing preferences (the latter is the situation when running Alva the first time).
Closing issue for now, please reopen with more information if the problem reappears.

**Closed by TheReincarnator** 2018-03-29 09:59 UTC
Labels: priority: high, type: bug

**Comment by jdanl89** [comment] 2018-11-22 00:34
I had this issue when I tried to do `app.on('ready', createWindow())`. It should be `app.on('ready', createWindow)`. **createWinodw** must be passed in as a reference, not as a function.
